# Generated by Django 4.2.11 on 2024-05-30 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VENTES', '0001_initial'),
        ('PRODUITS', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pharmacien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='produit',
            field=models.ManyToManyField(to='PRODUITS.produitvente'),
        ),
    ]
