# Generated by Django 4.2.11 on 2024-06-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUITS', '0003_rupture_de_stock_stock_en_peremption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_en_peremption',
            name='dosage',
        ),
    ]
